query ListAllMovies @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  movies {
    id
    title
    year
    genres
    runtimeMinutes
    summary
  }
}

query GetMovieById($id: UUID!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  movie(id: $id) {
    id
    title
    year
    genres
    runtimeMinutes
    summary
    createdAt
  }
}

mutation CreateNewMovieList($name: String!, $isPublic: Boolean!, $description: String) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  movieList_insert(data: {
    userId_expr: "auth.uid",
    name: $name,
    isPublic: $isPublic,
    description: $description,
    createdAt_expr: "request.time",
    updatedAt_expr: "request.time"
  }) {
    id
  }
}

query GetUserMovieLists @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  movieLists(where: { userId: { eq_expr: "auth.uid" } }) {
    id
    name
    isPublic
    description
    createdAt
    updatedAt
  }
}